version: '3.7'
services:
  web:
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    volumes:
      - .:/var/www/html
      - /var/www/html/var
      - /var/www/html/vendor
    ports:
      - "1235:80"